	var initialItems = [
{ id:"bizlegal-structure", orderA:1, orderB:1, url:"http://www.sba.gov/category/navigation-structure/starting-managing-business/starting-business/choose-your-business-stru", tags:"business, startup", title:"Choose Your Business Structure", type:"text", description:"deeper explanations and pros/cons of different business types" },
{ id:"bizlegal-type", orderA:2, orderB:1, url:"http://integratedbusinessguard.com/images/business-type-comparison-table.png", tags:"business, startup", title:"Business Type Comparison Chart", type:"image", description:"Chart for comparing the different aspects of types of businesses" },
{ id:"bizlegal-execsummary", orderA:3, orderB:1, url:"http://www.sba.gov/content/business-plan-executive-summary", tags:"business, executive summary", title:"Business Plan Executive Summary", type:"text", description:"What to include and how to frame your executive summary. Do this writing stuff BEFORE you legally start your business." },
{ id:"bizlegal-summary", orderA:4, orderB:1, url:"http://www.inc.com/guides/2010/08/how-to-write-a-summary-business-plan.html", tags:"business, buisness plan", title:"How to Write a Summary Business Plan", type:"text", description:"A succinct report on different points to cover in your business plan" },
{ id:"bizlegal-register", orderA:5, orderB:1, url:"http://www.sba.gov/content/register-with-state-agencies", tags:"business, startup", title:"Register With State Agencies", type:"text", description:"Has the full selections of state links for the forms to legally create your business, with notes on procedure, and state and franchise tax amounts and forms. " },
{ id:"bizlegal-ein", orderA:6, orderB:1, url:"http://www.ein-gov.us/index.php", tags:"business, IRS resource", title:"Govservices EIN application", type:"text", description:"IRS official EIN number application" },
{ id:"bizlegal-taxes", orderA:7, orderB:1, url:"http://www.irs.gov/Businesses/Small-Businesses-&-Self-Employed/Business-Taxes", tags:"Business, IRS resources", title:"Business Taxes", type:"text", description:"IRS list and form links for the different federal businesses taxes (remember there are state taxes too)" },
{ id:"bizlegal-fileelec", orderA:7, orderB:2, url:"http://www.irsvideos.gov/SmallBusinessTaxpayer/virtualworkshop/Lesson3", tags:"Business, IRS resources", title:"How to file and pay your taxes electronically", type:"course", description:"A video based workshop on what and how to file your business taxes" },
{ id:"bizlegal-taxcalendar", orderA:8, orderB:1, url:"http://www.tax.gov/calendar/", tags:"Business taxes, IRS resources", title:"Business Tax Calender", type:"text", description:"A monthly calender of dates for various tax submissions" },
{ id:"bizlegal-statetax", orderA:9, orderB:1, url:"http://www.sba.gov/content/learn-about-your-state-and-local-tax-obligations", tags:"Business, taxes", title:"Determine Your State Tax Obligations", type:"text", description:"Find your state tax requirements, forms, worker's comp, and unemployment" },
{ id:"bizlegal-sba", orderA:10, orderB:1, url:"http://www.sba.gov/local-assistance", tags:"Business, startup", title:"Local Small Business Assistance", type:"text", description:"Find free consulting resources in you area for different business aspects" },
{ id:"bizlegal-taxworkshop", orderA:10, orderB:2, url:"http://www.irs.gov/Businesses/Small-Businesses-&-Self-Employed/Small-Business-Tax-Workshops-and--Webinars", tags:"Business, startup", title:"Small Business Tax Workshops and Webinars", type:"event", description:"Find workshops in your state, many free, to work out problems and get live help." }
	];
