	var initialItems = [
{ id:"guitar-select", orderA:1, orderB:1, url:"http://www.youtube.com/watch?v=BjfLZGT8bmI", tags:"guitar selection", title:"Absolute beginners how to choose a guitar", type:"video", description:"Different types of guitars, how they sound, what kind of music are they good for." },
{ id:"guitar-intro", orderA:1, orderB:2, url:"https://www.coursera.org/course/guitar?from_restricted_preview=1&course_id=970244&r=https%3A%2F%2Fclass.coursera.org%2Fguitar-001%2Fauth%2Fauth_redirector%3Ftype%3Dlogin%26subtype%3Dnormal%26visiting%3Dhttps%253A%252F%252Fclass.coursera.org%252Fguitar-001%252Flecture%252F5", tags:"MOOC, guitar", title:"Introduction to Guitar", type:"course", description:"A course that covers all the differen introductory guitar information. Only runs at certain times. If you take this course, only do steps 7 and 9 for practice." },
{ id:"guitar-parts", orderA:2, orderB:1, url:"http://www.magnoliaguitar.com/wp-content/uploads/2010/07/Guitar-Diagram.png", tags:"guitar", title:"Acoustic and Electric Guitar Parts", type:"image", description:"image showing the different parts of electric and acoustic guitars" },
{ id:"guitar-tune", orderA:3, orderB:1, url:"http://www.howtotuneaguitar.org/", tags:"tuning widget, key selection, guitars", title:"How to tune a guitar", type:"game", description:"A tuning app with a varitey of keys to tune in, and explanations of uses for that key." },
{ id:"guitar-strum", orderA:4, orderB:1, url:"http://www.youtube.com/watch?v=JAnIV0tMtrU", tags:"picks, strumming", title:"Basic Strumming for Guitar", type:"video", description:"An exellent tutorial on how to hold your pick, and strumming with different beats. Pause after each section and practice that strumming technique before you move on. " },
{ id:"guitar-frets", orderA:5, orderB:1, url:"http://fingerstofrets.com/img/righty-charts/A7v4.png", tags:"guitar", title:"Fingers to Frets", type:"image", description:"image showing how the finger numbering is used for chords" },
{ id:"guitar-chords", orderA:6, orderB:1, url:"http://www.freeguitarvideos.com/Images/guitar-chords-chart.jpg", tags:"guitar, guitar chords", title:"Basic Guitar Chords", type:"image", description:"Standard chords and hand positions" },
{ id:"guitar-tabs", orderA:7, orderB:1, url:"http://www.heartwoodguitar.com/chords/", tags:"Guitar chords, strumming", title:"Free Guitar Chords, Tabs, Lyrics, etc.", type:"text", description:"Selections of songs to do simple strumming practices to. Select a couple favorites, go for the ones with S so you can watch a video if you get stuck. " },
{ id:"guitar-fingerstyle", orderA:8, orderB:1, url:"http://www.youtube.com/watch?v=8UU4yMkDdBw", tags:"guitar, fingerstyle", title:"Ultimate Beginner Fingerstyle Lesson", type:"video", description:"Simple exercises to learn basic fingerstyle techniques and tips. Follow along on your guitar, repeat till you have it!" },
{ id:"guitar-rocksmith", orderA:9, orderB:1, url:"http://rocksmith.ubi.com/rocksmith/en-us/home/index.aspx", tags:"game, guitar", title:"Rocksmith Authentic Guitar Game", type:"game", description:"If you want to consolidate your learning, and have some fun, give this a try." }
	];
